#
# rtfpessoa bash settings
#

DOTFILES_DEFAULT="$HOME/.$(whoami)rc"
DOTFILES=${DOTFILES-$DOTFILES_DEFAULT}

if [ -d "$DOTFILES" ]; then
	if [[ "$OSTYPE" == "darwin"* ]]; then
		# Theme
		source $DOTFILES/shells/bash/themes/agnoster/agnoster.bash
	fi

	# Customize to your needs...
	for config_file in "$(ls $DOTFILES/shells/posix/*)"; do source $config_file; done
fi
