#
# rtfpessoa bash settings
#

source $HOME/.bashrc
if [ -e /Users/rtfpessoa/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/rtfpessoa/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
