#
# Prezto configuration
# Author: rtfpessoa
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
DOTFILES_DIR_DEFAULT="$HOME/.$(whoami)rc"
DOTFILES_DIR=${DOTFILES_DIR-$DOTFILES_DIR_DEFAULT}
if [ -d "$DOTFILES_DIR" ]; then
  for config_file ($DOTFILES_DIR/zsh/*.zsh) source $config_file
  for config_file ($DOTFILES_DIR/shells/sources/*) source $config_file
fi

# Add some patterns
ZSH_HIGHLIGHT_PATTERNS+=('rm -*f*' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('git rhh*' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('git reset --hard*' 'fg=white,bold,bg=red')
