#
# Prezto configuration
# Author: rtfpessoa
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
DOTFILES_DEFAULT="$HOME/.$(whoami)rc"
DOTFILES=${DOTFILES-$DOTFILES_DEFAULT}
if [ -d "$DOTFILES" ]; then
  for config_file ($DOTFILES/zsh/*.zsh) source $config_file
  for config_file ($DOTFILES/shells/sources/*) source $config_file
fi

# Add some patterns
ZSH_HIGHLIGHT_PATTERNS+=('rm -*f*' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('git rhh*' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_PATTERNS+=('git reset --hard*' 'fg=white,bold,bg=red')

export GPG_TTY=$(tty)
